[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /logs/*.log
    Tag          fastapi.*

[OUTPUT]
    Name         es
    Match        *
    Host         elasticsearch
    Port         9200
    Index        url-shortener